public class Main
{
    public static void main(String[] args)
    {
        try
        {
            int arr[]= new int[5];
            System.out.println("Inside the try block");
            arr[5]=50/0;
            System.out.println(arr[5]);
        }
        
        catch(ArithmeticException e)
        {
            System.out.println("Arithmetic Exception occurs");
        }
        
        catch(ArrayIndexOutOfBoundsException e)
        {
            System.out.println("Array out of boound Exception occurs");
        }
        
        catch(Exception e)
        {
            System.out.println("Parent Exception occurs");
        }
        
        finally
        {
            System.out.println("Inside the finally block");
        }
    }
}
